### ISSUE TITLE
Need a way to omit a specific check

### ISSUE THREAD

**Issue by webJose** [bluwy/publint#119]
Hello!  My Vite plug-in [vite-plugin-single-spa](https://github.com/WJSoftware/vite-plugin-single-spa) specifies `exports["./ex"]` for TypeScript support, but the module is injected by the plug-in during runtime (`npm run dev` or `npm run build`).  Therefore, the `./ex` folder only contains the .d.ts file.

However, there must be a condition or importing doesn't work.  So `exports["./ex"].imports` is set to a fictitious `index.js` file.  This makes everything work, but `publint` is not happy:  "There is no `index.js` file in ./ex."

I tried adding index.js file with the content `export {}`, but then rollup tries to use it as opposed to the plug-in providing it in runtime.

My request for help:  How can I make both rollup and publint happy?  And if there's no way to make both happy, can publint provide an option to silence this particular error?

Many thanks!

**Comment by webJose** [comment]
I mean exactly what you understood:  Just "types" doesn't work.  I tried it.

**Comment by bluwy** [comment]
What exactly doesn't work? Auto-imports, intellisense, Vite/Rollup runtime, or something else?

**Comment by webJose** [comment]
Let me reproduce the error so I can answer precisely.  I'll come back.

I agree, publint is probably emitting a valid error because it doesn't know that the requirement will be fulfilled by my plug-in once Vite asks for it.  Vite works with a level of indirection, where it asks its plug-ins "do you know this guy?", and if a plug-in knows it, the plug-in is queried for its source code.

**Comment by webJose** [comment]
Apologies for the delay.

If I only have "types" and no condition, then trying to build a project that uses `vite-plugin-single-spa` results in the following error:

```plaintext
error during build:
[commonjs--resolver] No known conditions for "./ex" specifier in "vite-plugin-single-spa" package 
    at e (file:///C:/Users/webJo/src/ViteV6Test/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:15283:25)
    at n (file:///C:/Users/webJo/src/ViteV6Test/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:15283:650)
    at o (file:///C:/Users/webJo/src/ViteV6Test/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:15283:1301)
    at resolveExportsOrImports (file:///C:/Users/webJo/src/ViteV6Test/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16481:18)
    at resolveDeepImport (file:///C:/Users/webJo/src/ViteV6Test/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16494:25)
    at tryNodeResolve (file:///C:/Users/webJo/src/ViteV6Test/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16324:18)
    at Object.resolveId (file:///C:/Users/webJo/src/ViteV6Test/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:16109:19)
    at Object.handler (file:///C:/Users/webJo/src/ViteV6Test/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:51064:15)
    at file:///C:/Users/webJo/src/ViteV6Test/node_modules/rollup/dist/es/shared/node-entry.js:20874:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///C:/Users/webJo/src/ViteV6Test/node_modules/rollup/dist/es/shared/node-entry.js:20774:28)
```

**Comment by bluwy** [comment]
Vite is trying to resolve the import path from the logs. You should be able to avoid that in your plugin using the resolveId hook so you'd resolve the id yourself (eg prepend \0 to mark as virtual), and use enforce: "pre" or order: "pre" to run that hook before Vite's.

**Comment by webJose** [comment]
Thanks, @bluwy.  I just ran a quick test and it seems that making my existing `resolveId` hook `pre` seems to work as you predicted.  I'm glad I decided to open this issue.  I was not accounting for the order of things and you saw it clear as day.  Appreciated.

**Comment by bluwy** [comment]
Glad to hear that! I'll go ahead and close this issue for now then.
