### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by benmccann** [bluwy/publint#20]
```
vite/packages/vite$ pnpx publint deps
pnpm: Command failed with exit code 1: publint deps
    at makeError (~/.local/share/pnpm/global/5/.pnpm/pnpm@7.25.0/node_modules/pnpm/dist/pnpm.cjs:23105:17)
    at handlePromise (~/.local/share/pnpm/global/5/.pnpm/pnpm@7.25.0/node_modules/pnpm/dist/pnpm.cjs:23676:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler [as dlx] (~/.local/share/pnpm/global/5/.pnpm/pnpm@7.25.0/node_modules/pnpm/dist/pnpm.cjs:215806:7)
    at async ~/.local/share/pnpm/global/5/.pnpm/pnpm@7.25.0/node_modules/pnpm/dist/pnpm.cjs:223397:21
    at async main (~/.local/share/pnpm/global/5/.pnpm/pnpm@7.25.0/node_modules/pnpm/dist/pnpm.cjs:223366:34)
    at async runPnpm (~/.local/share/pnpm/global/5/.pnpm/pnpm@7.25.0/node_modules/pnpm/dist/pnpm.cjs:223596:5)
    at async ~/.local/share/pnpm/global/5/.pnpm/pnpm@7.25.0/node_modules/pnpm/dist/pnpm.cjs:223588:7
```

**Comment by bluwy** [comment]
I tested `pnpx publint deps` and it does work and logs the lint results, but since `process.exitCode` is `1` (because of an error), it looks like `pnpx` prints that message with the trace instead. So I don't think there's an issue here.

**Comment by benmccann** [comment]
Ahh. I see. I suppose that's reasonable then
